# Generated by Django 3.0.6 on 2020-11-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lg_distribuidora', '0003_remove_dado_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dado',
            name='palavras_chave',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
