# Generated by Django 3.0.6 on 2020-07-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=300)),
                ('logomarca', models.ImageField(blank=True, null=True, upload_to='logomarca')),
                ('endereço', models.CharField(max_length=300)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=11)),
                ('horario_de_atendimento', models.CharField(max_length=20)),
                ('nome_do_proprietário', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone_fixo', models.CharField(max_length=11)),
                ('celular_whatsapp', models.CharField(max_length=11)),
                ('breve_descrição_da_empresa', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_do_produto', models.CharField(max_length=30)),
                ('imagem_do_produto', models.ImageField(blank=True, null=True, upload_to='produtos')),
                ('Informações_sobre_o_produto', models.TextField(max_length=50)),
                ('preço', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='serviço',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_serviço', models.CharField(max_length=30)),
                ('imagem_do_serviço', models.ImageField(blank=True, null=True, upload_to='serviços')),
                ('Informações_sobre_o_serviço', models.TextField(max_length=50)),
                ('preço', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
