# Generated by Django 3.0.6 on 2020-05-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jc_contabilidade', '0002_dado'),
    ]

    operations = [
        migrations.AddField(
            model_name='dado',
            name='cnpj',
            field=models.CharField(default=11111, max_length=11),
            preserve_default=False,
        ),
    ]
