# Generated by Django 3.0.6 on 2020-05-15 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jc_contabilidade', '0003_dado_cnpj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dado',
            name='proprietario',
        ),
    ]
