# Generated by Django 3.0.6 on 2020-11-16 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jc_contabilidade', '0004_auto_20201115_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviço',
            name='Informações_sobre_o_serviço',
            field=models.TextField(max_length=200),
        ),
    ]
