# Generated by Django 3.0.6 on 2020-05-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jc_contabilidade', '0004_remove_dado_proprietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='dado',
            name='endereço',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dado',
            name='telefone_celular',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dado',
            name='telefone_fixo',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
