# Generated by Django 3.0.6 on 2020-05-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jc_contabilidade', '0005_auto_20200515_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='dado',
            name='nome_do_proprietário',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dado',
            name='sobrenome_do_proprietário',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
