# Generated by Django 3.0.6 on 2020-05-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jc_contabilidade', '0006_auto_20200515_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dado',
            old_name='sobrenome_do_proprietário',
            new_name='sobrenome',
        ),
    ]
