# Generated by Django 3.0.6 on 2020-05-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jc_contabilidade', '0007_auto_20200515_1624'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mídia',
            new_name='produto',
        ),
    ]
