# Generated by Django 3.0.6 on 2020-05-15 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jc_contabilidade', '0008_auto_20200515_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='anuncio',
            new_name='imagem_do_produto',
        ),
    ]
