# Generated by Django 3.0.6 on 2020-05-15 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jc_contabilidade', '0009_auto_20200515_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='descricao',
            new_name='descrição',
        ),
    ]
