# Generated by Django 3.0.6 on 2020-05-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jc_contabilidade', '0010_auto_20200515_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preço',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
