# Generated by Django 3.0.6 on 2020-05-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jc_contabilidade', '0011_produto_preço'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='nome_do_produto',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
