# Generated by Django 3.0.6 on 2020-05-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jc_contabilidade', '0012_produto_nome_do_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome_do_produto',
            field=models.CharField(max_length=20),
        ),
    ]
