# Generated by Django 3.0.6 on 2020-05-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jc_contabilidade', '0013_auto_20200515_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome_do_produto',
            field=models.CharField(max_length=30),
        ),
    ]
