# Generated by Django 3.0.6 on 2020-05-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jc_contabilidade', '0014_auto_20200515_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='serviço',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_serviço', models.CharField(max_length=30)),
                ('imagem_do_produto', models.ImageField(upload_to='')),
                ('descrição', models.CharField(max_length=100)),
                ('preço', models.FloatField()),
            ],
        ),
    ]
