# Generated by Django 3.0.6 on 2020-05-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jc_contabilidade', '0015_serviço'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descrição',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='serviço',
            name='descrição',
            field=models.TextField(max_length=100),
        ),
    ]
