# Generated by Django 3.0.6 on 2020-05-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jc_contabilidade', '0016_auto_20200515_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviço',
            name='imagem_do_produto',
        ),
        migrations.AddField(
            model_name='dado',
            name='logomarca',
            field=models.ImageField(blank=True, null=True, upload_to='logomarca'),
        ),
        migrations.AddField(
            model_name='serviço',
            name='imagem_do_serviço',
            field=models.ImageField(blank=True, null=True, upload_to='serviços'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem_do_produto',
            field=models.ImageField(blank=True, null=True, upload_to='produtos'),
        ),
    ]
