# Generated by Django 3.0.6 on 2020-05-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jc_contabilidade', '0017_auto_20200519_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='dado',
            name='breve_decrição_da_empresa',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviço',
            name='preço',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
