# Generated by Django 3.0.6 on 2020-05-21 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jc_contabilidade', '0018_auto_20200521_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dado',
            old_name='breve_decrição_da_empresa',
            new_name='breve_descrição_da_empresa',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='descrição',
            new_name='Informações_sobre_o_produto',
        ),
        migrations.RenameField(
            model_name='serviço',
            old_name='descrição',
            new_name='Informações_sobre_o_serviço',
        ),
    ]
