# Generated by Django 3.0.6 on 2020-05-22 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jc_contabilidade', '0020_auto_20200522_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='incremento',
            new_name='id',
        ),
    ]
