# Generated by Django 3.0.6 on 2020-05-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jc_contabilidade', '0021_auto_20200522_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='dado',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
