# Generated by Django 3.0.6 on 2020-05-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jc_contabilidade', '0022_dado_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='dado',
            name='cidade',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dado',
            name='estado',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
