# Generated by Django 3.0.6 on 2020-05-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jc_contabilidade', '0023_auto_20200523_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dado',
            name='telefone_celular',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='dado',
            name='telefone_fixo',
            field=models.CharField(max_length=11),
        ),
    ]
