# Generated by Django 3.0.6 on 2020-05-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jc_contabilidade', '0024_auto_20200524_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dado',
            old_name='telefone_celular',
            new_name='celular_whatsapp',
        ),
    ]
