# Generated by Django 3.0.6 on 2020-05-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jc_contabilidade', '0025_auto_20200524_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='dado',
            name='horario_de_atendimento',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='Informações_sobre_o_produto',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preço',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='serviço',
            name='Informações_sobre_o_serviço',
            field=models.TextField(max_length=50),
        ),
    ]
