# Generated by Django 3.0.6 on 2020-06-04 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conecte', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dado',
        ),
        migrations.DeleteModel(
            name='produto',
        ),
        migrations.DeleteModel(
            name='serviço',
        ),
    ]
