# Generated by Django 3.0.6 on 2020-06-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conecte', '0002_auto_20200604_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('logomarca', models.ImageField(blank=True, null=True, upload_to='logomarca')),
                ('endereço', models.CharField(max_length=300)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=11)),
                ('horario_de_atendimento', models.CharField(max_length=20)),
                ('nome_do_proprietário', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone_fixo', models.CharField(max_length=11)),
                ('celular_whatsapp', models.CharField(max_length=11)),
                ('breve_descrição_da_empresa', models.TextField()),
            ],
        ),
    ]
