# Generated by Django 3.0.6 on 2020-06-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conecte', '0003_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(max_length=15),
        ),
    ]
