# Generated by Django 3.0.6 on 2020-06-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conecte', '0004_auto_20200605_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone_fixo',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
