# Generated by Django 3.0.6 on 2020-06-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conecte', '0005_auto_20200605_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tenho_interesse_em_anunciar',
            field=models.CharField(blank=True, choices=[('produtos', 'produtos'), ('serviços', 'serviços'), ('produtos e serviços', 'produtos e serviços')], max_length=100, null=True),
        ),
    ]
