# Generated by Django 3.0.6 on 2020-06-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conecte', '0006_cliente_tenho_interesse_em_anunciar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('PI', 'PI'), ('SE', 'SE'), ('TO', 'TO')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tenho_interesse_em_anunciar',
            field=models.CharField(blank=True, choices=[('Produtos', 'Produtos'), ('Serviços', 'Serviços'), ('Produtos e serviços', 'Produtos e serviços')], max_length=50, null=True),
        ),
    ]
