# Generated by Django 3.0.6 on 2020-06-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conecte', '0007_auto_20200610_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='link_de_acesso',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
    ]
