# Generated by Django 3.0.6 on 2020-06-20 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conecte', '0008_cliente_link_de_acesso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='link_de_acesso',
        ),
    ]
