# Generated by Django 3.0.6 on 2020-06-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conecte', '0009_remove_cliente_link_de_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='atividade',
            field=models.CharField(choices=[('Açougue', 'Açougue'), ('Auto peças', 'Auto peças'), ('Farmácia', 'Farmácia'), ('Ferragista', 'Ferragista'), ('Lanchonete', 'Lanchonete'), ('Padaria', 'Padaria'), ('Pet Shop', 'Pet Shop'), ('Salão de beleza', 'Salão de beleza'), ('Supermercado', 'Supermercado'), ('', '')], default=0, max_length=100),
            preserve_default=False,
        ),
    ]
