# Generated by Django 3.0.6 on 2020-07-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conecte', '0010_cliente_atividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='observações',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='atividade',
            field=models.CharField(choices=[('Academia', 'Academia'), ('Açougue', 'Açougue'), ('Armarinhos', 'Armarinhos'), ('Auto peças', 'Auto peças'), ('Barbearia', 'Barbearia'), ('Distribuidora de bebidas', 'Distribuidora de bebidas'), ('Farmácia', 'Farmácia'), ('Ferragista', 'Ferragista'), ('Lanchonete', 'Lanchonete'), ('Loja de artigos para celulares', 'Loja de artigos para celulares'), ('Loja de calçados', 'Loja de calçados'), ('Loja de roupas', 'Loja de roupas'), ('Mercearia', 'Mercearia'), ('Panificadora', 'Panificadora'), ('Papelaria', 'Papelaria'), ('Pet Shop', 'Pet Shop'), ('Prestação de serviços', 'Prestação de serviços'), ('Restaurante', 'Restaurante'), ('Salão de beleza', 'Salão de beleza'), ('Supermercado', 'Supermercado'), ('Serviços de Advocacia', 'Serviços de Advocacia'), ('Serviços Contábeis', 'Serviços Contábeis'), ('Serviços Gerais', 'Serviços Gerais'), ('Serviços de Informática', 'Serviços de Informática'), ('Oficina de automóveis', 'Oficina de automóveis'), ('Outros', 'Outros')], max_length=100),
        ),
    ]
