# Generated by Django 3.0.6 on 2020-10-14 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conecte', '0012_cliente_cor_layout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cor_layout',
        ),
    ]
