# Generated by Django 3.0.6 on 2020-10-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conecte', '0015_auto_20201021_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='nome_do_proprietário',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='sobrenome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
