# Generated by Django 3.0.6 on 2020-10-21 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conecte', '0016_auto_20201021_0950'),
    ]

    operations = [
        migrations.DeleteModel(
            name='perfil',
        ),
    ]
