# Generated by Django 3.0.6 on 2020-10-22 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conecte', '0019_dado_produto_serviço'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dado',
        ),
        migrations.DeleteModel(
            name='produto',
        ),
        migrations.DeleteModel(
            name='serviço',
        ),
    ]
