# Generated by Django 3.0.6 on 2020-10-22 18:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conecte', '0020_auto_20201022_0818'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cliente',
            new_name='dado',
        ),
    ]
