# Generated by Django 3.0.6 on 2020-10-22 21:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conecte', '0021_auto_20201022_1545'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dado',
            new_name='cliente',
        ),
    ]
