# Generated by Django 3.0.6 on 2020-10-23 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conecte', '0022_auto_20201022_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
    ]
