# Generated by Django 3.0.6 on 2020-11-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conecte', '0024_cliente_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='palavras_chave',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
