# Generated by Django 3.0.6 on 2020-11-14 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conecte', '0025_cliente_palavras_chave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='palavras_chave',
        ),
    ]
